# This is based on the query used by anilist.co when you click on a specific anime
query AnilistDetails($id: Int, $type: MediaType, $isAdult: Boolean) {
	Media(id: $id, type: $type, isAdult: $isAdult) {
		id
		title {
			romaji
			english
			native
		}
		coverImage {
			extraLarge
			large
			medium
		}
		bannerImage
		startDate {
			year
			month
			day
		}
		endDate {
			year
			month
			day
		}
		description
		type
		format
		status(version: 2)
		episodes
		duration
		chapters
		volumes
		genres
		synonyms
		source(version: 3)
		isAdult
		meanScore
		averageScore
		popularity
		favourites
		trending
		hashtag
		countryOfOrigin
		characterPreview: characters(perPage: 6, sort: [ROLE, RELEVANCE, ID]) {
			edges {
				id
				role
				name
				voiceActors(language: JAPANESE, sort: [RELEVANCE, ID]) {
					id
					name {
						userPreferred
					}
					language: languageV2
				}
				node {
					id
					name {
						userPreferred
					}
					image {
						large
						medium
					}
				}
			}
		}
		studios(sort: [FAVOURITES_DESC]) {
			edges {
				isMain
				node {
					id
					name
				}
			}
		}
		tags {
			id
			name
			description
			rank
			isMediaSpoiler
			isGeneralSpoiler
		}
		mediaListEntry {
			id
			status
			score
		}
	}
}
